### ISSUE TITLE
Doesn't appear to work

### ISSUE THREAD

**Issue by grangej** [146BC/RomeBuild#3] opened 2016-05-16 18:27 UTC
attempting to do an upload / build, but it doesn't appear to work: 

`xcodes-mac-mini:regex jenkins$ romebuild --upload
**\* Checking out logger at "v1.1.1"

logger v1.1.1
Asset not found in Rome server, added to build list
Checkout project dependency logger
**\* Checking out logger at "v1.1.1"
Checkout inner dependencies for logger
**\* No Cartfile.resolved found, updating dependencies
Failed to read file or folder at /Users/Shared/Jenkins/Projects/regex/Carthage/Checkouts/logger/Cartfile: Error Domain=NSCocoaErrorDomain Code=260 "The file “Cartfile” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/Shared/Jenkins/Projects/regex/Carthage/Checkouts/logger/Cartfile, NSUnderlyingError=0x7fc460f12460 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Building logger for archive
**\* xcodebuild output can be found in /var/folders/dk/mzfwbnq16116dsz542734fdh000088/T/carthage-xcodebuild.ETwKU4.log
**\* Building scheme "Logger" in Logger.xcodeproj
**\* Found Carthage/Build/iOS/Logger.framework
**\* Found Carthage/Build/iOS/Logger.framework.dSYM
**\* Found Carthage/Build/iOS/6197A27C-2AD3-336C-A2DD-6533AAF80D48.bcsymbolmap
**\* Found Carthage/Build/iOS/6590B3AB-0C77-33F9-A606-52F03C41EDA2.bcsymbolmap
**\* Created /Users/Shared/Jenkins/Projects/regex/Logger.framework.zip
6 %
13 %
19 %
26 %
33 %
39 %
46 %
53 %
59 %
66 %
72 %
79 %
86 %
92 %
99 %
100 %
Upload complete
xcodes-mac-mini:regex jenkins$ romebuild --build
logger v1.1.1
Asset not found in Rome server, added to build list
**\* Checking out logger at "v1.1.1"
**\* xcodebuild output can be found in /var/folders/dk/mzfwbnq16116dsz542734fdh000088/T/carthage-xcodebuild.nO518Z.log
**\* Building scheme "Logger" in Logger.xcodeproj
`

**Comment by BernardGatt** [comment] 2016-05-16 20:03
Hey,

I tried to build the logger framework attached (made the main scheme shared and also added a tag test test with v1.1.1) but couldn't replicate the issue, framework is being uploaded properly and when the build command is run the framework is being extracted to the carthage build folder.

[Logger.zip](https://github.com/146BC/RomeBuild/files/266871/Logger.zip)
Can you please attach the Cartfile? so I can verify that one.

Bernard.

**Comment by grangej** [comment] 2016-05-16 20:23
It appears to be a problem with the install on Mac, I moved the server to a Ubuntu box and I no longer am seeing this issue. 

on the mac server I do see the following :

`5/16/16 11:52:22.000 AM kernel[0]: CODE SIGNING: cs_invalid_page(0x1036c5000): p=17256[romebuild] final status 0x0, allowing (remove VALID) page
`

**Comment by BernardGatt** [comment] 2016-05-17 07:37
Can you save the nodejs server log output to a file and attach it please?

I'd like to see before & after upload and before & after you build.

**Comment by BernardGatt** [comment] 2016-05-18 21:21
Since i'm actively testing on a Mac and haven't been able to reproduce, i'm closing this issue.

If you have the log please re-open and attach.

Thanks for reporting.

**Closed as completed by BernardGatt** 2016-05-18 21:21 UTC
